### PR TITLE
Codebase decoupling boilerplate

### PR DESCRIPTION
**Pull request by adipai**
Did an overhaul of the coding standards:
* decoupled the modules for easier scalabilty
* added docstrings to conform to pep8 standard
* replaced camel case with snake case throughout
* improved search feature

Have checked that the branch is stable, feel free to run your checks.

### CODE REVIEW

**Review by ananya173147 — APPROVED** [review]
Your code works

**Comment by rishi2019194** [comment]
Code works!

**Review by rishi2019194 — APPROVED** [review]
Your code works!

**Review by samarthshetty09 — APPROVED** [review]
Address build checks

**Comment by adipai** [comment]
Build checks are mostly PEP8 standards (moving goalpost, there's always something to do better). We can decide upon a threshold (based on size of codebase) now that the codebase is revamped and relatively conforms to the standard 2x times the original repository.

**Pull request merged**
